version: '3'

services:
  postgis:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
        - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d 'user=test_user dbname=test_db host=postgis' " ]
      interval: 5s
      timeout: 5s
      retries: 5

  geolocation:
    image: registry.incloud.vet/vet.inpulse/geolocation:0.0.2
    environment:
      POSTGRES_URL: jdbc:postgresql://postgis:5432/test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    depends_on:
      postgis:
        condition: service_healthy
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgis_data:
